# Conclusion
1.Market Cap: The market cap of the cryptos and traditional stocks basically follow the same trend in recent years, while the market cap of the cryptos expanded more rapidly. In the early years ADA and XRP shared a significant amount of crypto’s market capitalization. As Bitcoin has grown in popularity over the years, its market cap has increased many times over. However, in 2021 more and more other new cryptocurrency emerged and many new cryptos other than traditional ones, like BTC, ETH and XRP , had a significant market capitalization.
2. Price among cryptocurrencies: Bitcoin, Ethereum, XRP’s daily closing price basically follows linear relationship with each other and the slope of the linear relationship line is changed at the beginning of 2020. Before 2020, XRP closing price is higher than that after 2020 with the same ETH or BTC price.
3.Cryptos v.s stocks: Both the cryptocurrency, represented by Bitcoin and ETH, and the traditional financial assets, represented by the Nasdaq 100 index and DJI, their financial yield sequence of have the characteristics of peaks and thick tails, and the rate of return and volatility of encrypted cryptocurrency is greater after 2020.
4. Price v.s. Google Trend: There is a certain lag between the popularity on social media and the daily return of cryptocurrencies. Generally, the Google Trend index will increase significantly a few days after days when Bitcoin fluctuated violently.
5.Google Trend v.s State: Besides California, Washington, and New York , which are economically developed, show a high interest in Bitcoin, people in Nevada are the most ardent fan of Bitcoin,this result is due to Nevada’s easing policy on cryptocurrencies.
6.Related query: ‘Stock’ and ‘Ethereum’ are most related with Bitcoin search , which confirms that cryptocurrencies have strong correlations with each other and with traditional stocks.
